using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DATA.Entities
{
    public class Address
    {
        public int Id { get; set; } // Autogenerated PK Id
        [Required]
        [MaxLength(400)]
        public string Street { get; set; }
        [Required]
        [MaxLength(400)]
        public string City { get; set; }
        [Required]
        public string Country { get; set; } // Mandatory

        public ICollection<Student> Students { get; set; } // Navigation property
    }
}
