using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DATA.Entities
{
    public class Student
    {
        public int Id { get; set; } // Autogenerated PK Id
        [Required]
        [MaxLength(200)]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(400)]
        public string LastName { get; set; }
        [Required]
        public DateTime EnrollmentDate { get; set; }
        [Required]
        public DateTime DOB { get; set; }
        [Required]
        public string Mail { get; set; }
        [Required]
        [MaxLength(4)]
        public string StudentIndex { get; set; }
        [Required]
        public double GPA { get; set; }
        public int AddressId { get; set; } // FK Address Id
        public Address Address { get; set; } // Navigation property
    }
}
